version: "3.8"
services:
  laststand:
    image: ft/laststand
    container_name: laststand
    restart: always
    ports: 
      - "${VITE_HOST_PORT}:${VITE_HOST_PORT}"
    build:
      context: ./
      dockerfile: laststand/Dockerfile
  laststand-api:
    env_file:
      - ./.env
    image: ft/laststand-api
    container_name: laststand-api
    restart: always
    networks:
      - db-be
    ports: 
      - "${API_PORT}:${API_PORT}"
      - "${SOCKET_PORT}:${SOCKET_PORT}"
    build:
      context: ./
      dockerfile: laststand-api/Dockerfile
    depends_on:
      - laststand-db
  laststand-db:
    image: postgres
    container_name: laststand-db
    networks:
      - db-be
    restart: always
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: "${PG_USER}"
      POSTGRES_PASSWORD: "${PG_PASS}"
    volumes:
      - local_pgdata:/var/lib/postgresql/data

networks:
  fe-be:
    driver: bridge
  db-be:
    driver: bridge
  
volumes:
  local_pgdata:
  pgadmin-data: